### ISSUE TITLE
Install on AWS w/ TFS Server Error

### ISSUE THREAD

**Issue by zerosnap** [onlyutkarsh/ExportImportBuildDefinition#25] opened 2017-09-19 16:53 UTC
### Installed product versions
- Export/Import Buid Definition extension: 0.0.8

### Description
Install errors, saying products are missing.  

### Steps to recreate
1. Download extension
2. Transfer to AWS server through RDP
3. Install extension

### Current behavior
Error on install.

From log:

`9/19/2017 4:16:46 PM - Searching for applicable products...
9/19/2017 4:16:46 PM - Found installed product - Microsoft Visual Studio Professional 2013
9/19/2017 4:16:46 PM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
9/19/2017 4:16:46 PM - Found installed product - Microsoft Visual Studio Enterprise 2015
9/19/2017 4:16:46 PM - Found installed product - Microsoft Visual Studio Professional 2015
9/19/2017 4:16:46 PM - Found installed product - Microsoft Visual Studio Community 2015
9/19/2017 4:16:46 PM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
9/19/2017 4:16:46 PM - Found installed product - Global Location
9/19/2017 4:16:46 PM - Found installed product - Visual Studio Enterprise 2017
9/19/2017 4:16:46 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()`

### Expected behavior
The install should complete successfully since TFS Server 2017 IS installed there.

**Comment by onlyutkarsh** [comment] 2017-09-19 17:07
Seems duplicate of #12 - Please see my response.

**Closed by onlyutkarsh** 2017-09-19 17:07 UTC

**Comment by zerosnap** [comment] 2017-09-19 17:20
This solved my problem. Thank you, @onlyutkarsh
